import {
  Client,
  WorkOrder,
  MaintenanceContract,
  Route,
  Equipment,
  Crew,
} from "./types";

// ==================== CREWS ====================
export const crews: Crew[] = [
  {
    id: "crew-1",
    name: "Crew 1 — Diego",
    leadName: "Diego Reyes",
    members: ["Diego Reyes", "Marco Salinas", "Tony Vega"],
    truckId: "eq-truck-1",
    trailerId: "eq-trailer-1",
    phone: "(210) 555-0142",
    defaultRouteIds: ["route-1", "route-3"],
  },
  {
    id: "crew-2",
    name: "Crew 2 — Hector",
    leadName: "Hector Mendoza",
    members: ["Hector Mendoza", "Luis Ramirez"],
    truckId: "eq-truck-2",
    trailerId: "eq-trailer-2",
    phone: "(210) 555-0188",
    defaultRouteIds: ["route-2", "route-4"],
  },
  {
    id: "crew-3",
    name: "Crew 3 — Install / Specialty",
    leadName: "Ron Holcomb",
    members: ["Ron Holcomb", "Javier Cruz"],
    truckId: "eq-truck-3",
    phone: "(210) 555-0101",
    defaultRouteIds: [],
  },
];

// ==================== EQUIPMENT ====================
export const equipment: Equipment[] = [
  {
    id: "eq-truck-1",
    type: "vehicle",
    make: "Ford",
    model: "F-250 Super Duty",
    serialNumber: "1FT7W2BT5KEC42189",
    year: 2019,
    purchaseDate: "2019-03-12",
    purchasePrice: 48500,
    assignedCrewId: "crew-1",
    shopStatus: "in-service",
    hoursOrMileage: 84320,
    nextServiceDue: "2026-06-15",
    notes: "Oil change every 5k. New tires Mar 2026.",
    maintenanceLog: [
      { id: "ml-1", date: "2026-03-04", description: "4 new tires + alignment", cost: 1240, shop: "Discount Tire Stone Oak" },
      { id: "ml-2", date: "2026-01-22", description: "Oil change, rotate", cost: 89, shop: "Jiffy Lube" },
    ],
  },
  {
    id: "eq-truck-2",
    type: "vehicle",
    make: "Chevrolet",
    model: "Silverado 2500HD",
    serialNumber: "1GC4YPEY2MF128844",
    year: 2021,
    purchaseDate: "2021-08-04",
    purchasePrice: 52000,
    assignedCrewId: "crew-2",
    shopStatus: "in-service",
    hoursOrMileage: 51200,
    notes: "Trailer brake controller installed.",
    maintenanceLog: [
      { id: "ml-3", date: "2026-02-11", description: "Brake pads front", cost: 420, shop: "Mike's Garage" },
    ],
  },
  {
    id: "eq-truck-3",
    type: "vehicle",
    make: "Ford",
    model: "F-350 Dually",
    serialNumber: "1FT8W3DT8LEC11023",
    year: 2020,
    assignedCrewId: "crew-3",
    shopStatus: "needs-service",
    hoursOrMileage: 67400,
    nextServiceDue: "2026-05-01",
    notes: "DEF system warning light — needs diagnostic.",
    maintenanceLog: [],
  },
  {
    id: "eq-trailer-1",
    type: "trailer",
    make: "PJ Trailers",
    model: "16ft Utility",
    serialNumber: "PJ16UT-44892",
    year: 2020,
    assignedCrewId: "crew-1",
    shopStatus: "in-service",
    notes: "New deck boards Apr 2025.",
    maintenanceLog: [],
  },
  {
    id: "eq-trailer-2",
    type: "trailer",
    make: "Big Tex",
    model: "14ft Landscape",
    serialNumber: "BTX14LS-77231",
    year: 2022,
    assignedCrewId: "crew-2",
    shopStatus: "in-service",
    notes: "",
    maintenanceLog: [],
  },
  {
    id: "eq-mower-1",
    type: "mower",
    make: "Scag",
    model: "Tiger Cat II 52in",
    serialNumber: "STC2-2024-8841",
    year: 2024,
    purchasePrice: 11200,
    assignedCrewId: "crew-1",
    shopStatus: "in-service",
    hoursOrMileage: 412,
    serviceIntervalHours: 100,
    nextServiceDue: "2026-05-12",
    notes: "Primary unit. Blades sharpened 4/14.",
    maintenanceLog: [
      { id: "ml-4", date: "2026-04-14", description: "Blade sharpen + belt inspect", cost: 65 },
    ],
  },
  {
    id: "eq-mower-2",
    type: "mower",
    make: "Exmark",
    model: "Lazer Z X-Series 60in",
    serialNumber: "EXM-LZX60-11984",
    year: 2022,
    assignedCrewId: "crew-2",
    shopStatus: "in-service",
    hoursOrMileage: 1820,
    serviceIntervalHours: 100,
    notes: "Workhorse. Hydro fluid change due soon.",
    maintenanceLog: [],
  },
  {
    id: "eq-mower-3",
    type: "mower",
    make: "Toro",
    model: "TimeMaster 30in walk-behind",
    serialNumber: "TM30-2023-4421",
    year: 2023,
    assignedCrewId: "crew-1",
    shopStatus: "in-shop",
    notes: "At Stone's Outdoor Power — pull cord broken.",
    maintenanceLog: [
      { id: "ml-5", date: "2026-04-22", description: "Drop off — recoil starter", cost: 0, shop: "Stone's Outdoor Power" },
    ],
  },
  {
    id: "eq-trim-1",
    type: "trimmer",
    make: "Stihl",
    model: "FS 91 R",
    serialNumber: "STIHL-FS91-882144",
    year: 2024,
    assignedCrewId: "crew-1",
    shopStatus: "in-service",
    notes: "",
    maintenanceLog: [],
  },
  {
    id: "eq-trim-2",
    type: "trimmer",
    make: "Stihl",
    model: "FS 131",
    serialNumber: "STIHL-FS131-771203",
    year: 2023,
    assignedCrewId: "crew-2",
    shopStatus: "in-service",
    notes: "",
    maintenanceLog: [],
  },
  {
    id: "eq-edger-1",
    type: "edger",
    make: "Echo",
    model: "PE-225",
    serialNumber: "ECHO-PE225-552188",
    assignedCrewId: "crew-1",
    shopStatus: "in-service",
    notes: "",
    maintenanceLog: [],
  },
  {
    id: "eq-blower-1",
    type: "blower",
    make: "Stihl",
    model: "BR 800 X",
    serialNumber: "STIHL-BR800-99041",
    assignedCrewId: "crew-1",
    shopStatus: "in-service",
    notes: "Backpack blower.",
    maintenanceLog: [],
  },
  {
    id: "eq-combo-1",
    type: "combo-unit",
    make: "Stihl",
    model: "KombiSystem KM 131 R",
    serialNumber: "STIHL-KM131-44021",
    assignedCrewId: "crew-3",
    shopStatus: "in-service",
    notes: "Attachments: pole pruner, hedge trim, edger.",
    maintenanceLog: [],
  },
];

// ==================== CLIENTS ====================
export const clients: Client[] = [
  {
    id: "cl-001",
    name: "The Whitlock Residence",
    address: "18204 Sonterra Place",
    city: "San Antonio",
    zip: "78258",
    phone: "(210) 555-2891",
    email: "k.whitlock@gmail.com",
    gateCode: "#4421*",
    serviceNotes: "Premier weekly account. Edges crisp, mow at 3.5\". Owner notices everything.",
    maintenanceFrequency: "weekly",
    propertyInstructions: "Park on street, NOT driveway (sealed). Side gate on east. Two large dogs — text Kara before arriving: (210) 555-2891.",
    crewNotes: "Diego is preferred lead. Mrs. Whitlock often home Tue mornings — be friendly but quick.",
    equipmentNotes: "Back gate is 38\" wide — only the 30\" walk-behind fits. NO Z-turn in back yard.",
    contaminationNotes: "Pristine St. Augustine. Blow off mowers before entering. Just had grub treatment Apr 18.",
    beforeAfterPhotos: [],
    tags: ["premier", "weekly", "stone-oak"],
    createdAt: "2022-03-14",
  },
  {
    id: "cl-002",
    name: "Garza, Miguel & Anna",
    address: "342 Heritage Oak Dr",
    city: "San Antonio",
    zip: "78258",
    phone: "(210) 555-1142",
    email: "miguel.garza@hotmail.com",
    gateCode: "8842",
    serviceNotes: "Biweekly maintenance + spring/fall cleanup add-on.",
    maintenanceFrequency: "biweekly",
    propertyInstructions: "Side gate code 8842. Pool equipment area — keep clippings out. Cat is indoor only.",
    crewNotes: "Anna handles billing — invoice to her email.",
    equipmentNotes: "Standard. Z-turn fits.",
    contaminationNotes: "Some chinch bug damage in front. Treated 4/02.",
    beforeAfterPhotos: [],
    tags: ["biweekly", "stone-oak"],
    createdAt: "2023-06-22",
  },
  {
    id: "cl-003",
    name: "Buffalo Crossing HOA — Common Areas",
    address: "Multiple — see route",
    city: "San Antonio",
    zip: "78230",
    phone: "(210) 555-9920",
    email: "manager@buffalocrossinghoa.org",
    serviceNotes: "Weekly mow + hedge trim quarterly + mulch refresh in March.",
    maintenanceFrequency: "weekly",
    propertyInstructions: "5 entry monuments, 3 detention ponds, pool common area. Map in truck.",
    crewNotes: "Property manager Sandra walks property Friday mornings. Avoid Friday AM if possible.",
    equipmentNotes: "Need 60\" deck for entry medians. Pond banks too steep — string trim only, no mower.",
    contaminationNotes: "Detention pond #2 has bermuda invading from neighbor. Don't track into common turf.",
    beforeAfterPhotos: [],
    tags: ["commercial", "hoa", "weekly", "high-value"],
    createdAt: "2021-01-15",
  },
  {
    id: "cl-004",
    name: "Reyna, Patricia",
    address: "904 Magnolia Bend",
    city: "San Antonio",
    zip: "78212",
    phone: "(210) 555-3344",
    email: "patti.reyna@yahoo.com",
    serviceNotes: "Monthly maintenance — heavy beds, light turf.",
    maintenanceFrequency: "monthly",
    propertyInstructions: "Historic Monte Vista. Tight street parking. No power tools before 8am — neighbor complained.",
    crewNotes: "Owner is retired teacher. Loves to chat — budget extra 10 min.",
    equipmentNotes: "Use 21\" push only — beds wrap entire property.",
    contaminationNotes: "Heirloom roses by porch — no trimmer string near them.",
    beforeAfterPhotos: [],
    tags: ["monthly", "monte-vista", "historic"],
    createdAt: "2024-09-01",
  },
  {
    id: "cl-005",
    name: "Cedar Ridge Office Park",
    address: "12500 Cedar Ridge Dr",
    city: "San Antonio",
    zip: "78230",
    phone: "(210) 555-7700",
    email: "facilities@cedarridgeop.com",
    gateCode: "Use intercom — call Frank ext 102",
    serviceNotes: "Weekly commercial. 4 buildings, 2.3 acres total turf.",
    maintenanceFrequency: "weekly",
    propertyInstructions: "Service before 7am Mon/Wed (tenant request). Dumpster area off limits — tenant trash only.",
    crewNotes: "Frank Decker is property contact. Invoices NET 30, EFT.",
    equipmentNotes: "60\" Z-turn ideal. Bring backpack blower for sidewalks.",
    contaminationNotes: "Recently sprayed pre-emergent — be aware re: sensitive landscape beds at building C.",
    beforeAfterPhotos: [],
    tags: ["commercial", "weekly", "high-value"],
    createdAt: "2020-04-10",
  },
  {
    id: "cl-006",
    name: "Kowalski, Jim",
    address: "27 Lakeview Trail",
    city: "Boerne",
    zip: "78006",
    phone: "(830) 555-0091",
    email: "jkowalski@me.com",
    gateCode: "Open — long driveway",
    serviceNotes: "Biweekly + irrigation check monthly. 1.2 acre lot.",
    maintenanceFrequency: "biweekly",
    propertyInstructions: "Hill country property. Watch for snakes in rock areas. Owner often travels.",
    crewNotes: "Pay by check, mailed monthly. Reliable.",
    equipmentNotes: "Need 60\" + 52\" both. Lots of slope — no Z-turn on east bank.",
    contaminationNotes: "Cedar fever zone. Lots of native plants — don't trim live oaks Feb-June (oak wilt).",
    beforeAfterPhotos: [],
    tags: ["biweekly", "boerne", "acreage"],
    createdAt: "2023-02-19",
  },
];

// ==================== CONTRACTS ====================
export const contracts: MaintenanceContract[] = [
  {
    id: "ct-001",
    clientId: "cl-001",
    frequency: "weekly",
    routeId: "route-1",
    crewId: "crew-1",
    monthlyValue: 520,
    recurringPrice: 130,
    firstCleanupFee: 0,
    startDate: "2022-03-21",
    addOns: [
      { id: "ao-1", name: "Hedge trim", monthlyValue: 60, frequency: "quarterly" },
      { id: "ao-2", name: "Spring mulch refresh", monthlyValue: 35, frequency: "annual" },
    ],
    active: true,
    notes: "Long-term anchor account. Renewed 2026.",
  },
  {
    id: "ct-002",
    clientId: "cl-002",
    frequency: "biweekly",
    routeId: "route-1",
    crewId: "crew-1",
    monthlyValue: 220,
    recurringPrice: 110,
    firstCleanupFee: 350,
    startDate: "2023-06-29",
    addOns: [
      { id: "ao-3", name: "Spring + fall cleanup", monthlyValue: 50, frequency: "biannual" },
    ],
    active: true,
    notes: "",
  },
  {
    id: "ct-003",
    clientId: "cl-003",
    frequency: "weekly",
    routeId: "route-2",
    crewId: "crew-2",
    monthlyValue: 3800,
    recurringPrice: 950,
    firstCleanupFee: 1200,
    startDate: "2021-01-22",
    addOns: [
      { id: "ao-4", name: "Quarterly hedge trim", monthlyValue: 240, frequency: "quarterly" },
      { id: "ao-5", name: "March mulch refresh", monthlyValue: 180, frequency: "annual" },
      { id: "ao-6", name: "Pond bank string trim", monthlyValue: 120, frequency: "monthly" },
    ],
    active: true,
    notes: "Anchor commercial account. Renews Jan annually.",
  },
  {
    id: "ct-004",
    clientId: "cl-004",
    frequency: "monthly",
    routeId: "route-3",
    crewId: "crew-1",
    monthlyValue: 165,
    recurringPrice: 165,
    firstCleanupFee: 280,
    startDate: "2024-09-08",
    addOns: [],
    active: true,
    notes: "",
  },
  {
    id: "ct-005",
    clientId: "cl-005",
    frequency: "weekly",
    routeId: "route-2",
    crewId: "crew-2",
    monthlyValue: 2400,
    recurringPrice: 600,
    firstCleanupFee: 0,
    startDate: "2020-04-17",
    addOns: [
      { id: "ao-7", name: "Sidewalk blow-down add'l Fri", monthlyValue: 200, frequency: "weekly" },
    ],
    active: true,
    notes: "EFT auto-pay, NET 30 invoicing.",
  },
  {
    id: "ct-006",
    clientId: "cl-006",
    frequency: "biweekly",
    routeId: "route-4",
    crewId: "crew-2",
    monthlyValue: 380,
    recurringPrice: 190,
    firstCleanupFee: 600,
    startDate: "2023-03-04",
    addOns: [
      { id: "ao-8", name: "Monthly irrigation check", monthlyValue: 75, frequency: "monthly" },
    ],
    active: true,
    notes: "Boerne route — only on Wednesdays.",
  },
];

// ==================== ROUTES ====================
export const routes: Route[] = [
  {
    id: "route-1",
    name: "Stone Oak Tuesday",
    dayOfWeek: "Tue",
    zipCodes: ["78258", "78259"],
    crewId: "crew-1",
    truckId: "eq-truck-1",
    trailerId: "eq-trailer-1",
    stops: [
      { clientId: "cl-001", contractId: "ct-001", estimatedMinutes: 45, order: 1 },
      { clientId: "cl-002", contractId: "ct-002", estimatedMinutes: 35, order: 2 },
    ],
    weeklyRevenue: 240,
    estimatedDriveMinutes: 35,
    estimatedJobMinutes: 80,
  },
  {
    id: "route-2",
    name: "NW Commercial Mon/Wed",
    dayOfWeek: "Mon",
    zipCodes: ["78230"],
    crewId: "crew-2",
    truckId: "eq-truck-2",
    trailerId: "eq-trailer-2",
    stops: [
      { clientId: "cl-005", contractId: "ct-005", estimatedMinutes: 180, order: 1 },
      { clientId: "cl-003", contractId: "ct-003", estimatedMinutes: 240, order: 2 },
    ],
    weeklyRevenue: 1550,
    estimatedDriveMinutes: 25,
    estimatedJobMinutes: 420,
  },
  {
    id: "route-3",
    name: "Inner Loop Friday",
    dayOfWeek: "Fri",
    zipCodes: ["78212", "78215"],
    crewId: "crew-1",
    truckId: "eq-truck-1",
    trailerId: "eq-trailer-1",
    stops: [
      { clientId: "cl-004", contractId: "ct-004", estimatedMinutes: 90, order: 1 },
    ],
    weeklyRevenue: 41.25,
    estimatedDriveMinutes: 40,
    estimatedJobMinutes: 90,
  },
  {
    id: "route-4",
    name: "Boerne Wednesday",
    dayOfWeek: "Wed",
    zipCodes: ["78006", "78015"],
    crewId: "crew-2",
    truckId: "eq-truck-2",
    trailerId: "eq-trailer-2",
    stops: [
      { clientId: "cl-006", contractId: "ct-006", estimatedMinutes: 110, order: 1 },
    ],
    weeklyRevenue: 95,
    estimatedDriveMinutes: 70,
    estimatedJobMinutes: 110,
  },
];

// ==================== WORK ORDERS ====================
export const workOrders: WorkOrder[] = [
  {
    id: "wo-001",
    number: "WO-2026-0142",
    clientId: "cl-001",
    propertyAddress: "18204 Sonterra Place",
    jobType: "install",
    description: "Replace 18 dwarf yaupon hollies along north bed. Prep, plant, mulch, water-in.",
    beforePhotos: [],
    afterPhotos: [],
    notes: "Mrs. Whitlock approved on 4/22. Plants ordered from Fanick's.",
    materials: [
      { id: "m-1", description: "Dwarf yaupon holly 5gal", quantity: 18, unit: "ea", unitCost: 22, markup: 1.4 },
      { id: "m-2", description: "Premium hardwood mulch", quantity: 4, unit: "yd", unitCost: 32, markup: 1.3 },
      { id: "m-3", description: "Compost amendment", quantity: 2, unit: "yd", unitCost: 38, markup: 1.3 },
    ],
    laborHoursEstimated: 14,
    laborRate: 75,
    crewSize: 2,
    status: "scheduled",
    scheduledFor: "2026-05-06",
  },
  {
    id: "wo-002",
    number: "WO-2026-0141",
    clientId: "cl-006",
    propertyAddress: "27 Lakeview Trail, Boerne",
    jobType: "cleanup",
    description: "Cedar fever cleanup — remove fallen branches, haul debris, blow down all hardscape.",
    beforePhotos: [],
    afterPhotos: [],
    notes: "Quoted on-site 4/24. Approved by phone.",
    materials: [
      { id: "m-4", description: "Dump fee — green waste", quantity: 1, unit: "load", unitCost: 85, markup: 1.0 },
    ],
    laborHoursEstimated: 6,
    laborHoursActual: 5.5,
    laborRate: 75,
    crewSize: 2,
    status: "completed",
    scheduledFor: "2026-04-29",
    completedAt: "2026-04-29",
    invoiceNumber: "INV-2026-0301",
    invoiceTotal: 910,
    paymentNotes: "Net 15. Check expected by 5/14.",
  },
  {
    id: "wo-003",
    number: "WO-2026-0138",
    clientId: "cl-003",
    propertyAddress: "Buffalo Crossing HOA Common Areas",
    jobType: "hardscape",
    description: "Repair limestone monument border at main entrance — 12 stones reset, polymeric sand refresh.",
    beforePhotos: [],
    afterPhotos: [],
    notes: "Bid against two others. Won on track record.",
    materials: [
      { id: "m-5", description: "Polymeric sand 50lb", quantity: 6, unit: "bag", unitCost: 28, markup: 1.35 },
      { id: "m-6", description: "Replacement limestone caps", quantity: 4, unit: "ea", unitCost: 45, markup: 1.4 },
    ],
    laborHoursEstimated: 18,
    laborRate: 85,
    crewSize: 3,
    status: "in-progress",
    scheduledFor: "2026-04-28",
  },
  {
    id: "wo-004",
    number: "WO-2026-0139",
    clientId: "cl-002",
    propertyAddress: "342 Heritage Oak Dr",
    jobType: "irrigation",
    description: "Replace 3 broken pop-up heads in front zone, adjust spray pattern on zone 2.",
    beforePhotos: [],
    afterPhotos: [],
    notes: "Spotted during routine mow.",
    materials: [
      { id: "m-7", description: "Hunter Pro-Spray 4\" pop-up", quantity: 3, unit: "ea", unitCost: 8.5, markup: 1.5 },
    ],
    laborHoursEstimated: 1.5,
    laborRate: 75,
    crewSize: 1,
    status: "draft",
  },
];
